### ISSUE TITLE
<code> tag styling

### ISSUE THREAD

**Issue by nekoyoubi** [itchio/itch.io#1424]
I was inspecting some HTML after I wrote a post with various markdown inline code lines (e.g. \`these\` -> `these`), and I noticed that they were there, as in being properly generated in the HTML, but styled undetectable. At first I thought something was going on where an extension (Dark Reader, amirite) was maybe manipulating them so I disabled it; no dice.

Could this maybe get some love in the styles? I mean, I can always just add myself a CSS override for the site, but then what fixes it for me means nothing for my formatting to others.

Using github's aesthetics as a base, here's what looks decent to me (in the dark mode at least; would obviously need some tweaking for light backgrounds):

``` css
code {
	padding: .15em .3em;
	margin: 0;
	font-size: 85%;
	white-space: break-spaces;
	background-color: rgba(255,255,255,.15);
	border-radius: 6px;
}
```

Images of without and with below.

![Without restyling the code-block](https://i.imgur.com/ZKxotRQ.png)
![After restyling the code-block](https://i.imgur.com/6FrH4HT.png)
