### ISSUE TITLE
FR: trim in-profile collection descriptions to first line/paragraph

### ISSUE THREAD

**Issue by YellowAfterlife** [itchio/itch.io#1650]
**Is your feature request related to a problem? Please describe.**

Suppose I have a collection description:  
![image](https://github.com/user-attachments/assets/2ae7595a-ca92-4fcd-bbbe-dd23c2010a7d)  
Very nice.

However, on profile pages these are shown as single-line plaintext snip, which is slightly less nice:
![image](https://github.com/user-attachments/assets/0fb673a8-a004-4dbe-aa50-1ba92423464b)

And since it's plaintext, I can't really fix this with custom CSS either

**Describe the solution you'd like**

Only show the plaintext of the collection description up to the end of first paragraph (or until the first BR).

**Describe alternatives you've considered**

Doing this at the moment:
```css
.collection_row[data-collection_id="4749242"] .collection_description {
font-size: 0;
}
.collection_row[data-collection_id="4749242"] .collection_description:before {
content: "These let you do various cool/useful things on Windows! (and, sometimes, other platforms)";
font-size: 1rem;
}
```

**Additional context**
No particular rush
